[package]
name = "cbuffer"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atty = "0.2.14"
clap = { version = "3.1.17", features = ["derive"] }
queues = "1.1.0"
raw_tty = "0.1.0"
